#!/bin/sh
### BEGIN INIT INFO
# Provides:          wb-homa-gpio
# Default-Start:     2 3 4 5 ??
# Default-Stop:      0 1 6 ??
# Required-Start: $remote_fs mosquitto
# Required-Stop: $remote_fs
# Short-Description: MQTT Driver for RFM69
# Description:       MQTT Driver for RFM69
### END INIT INFO

# Author: Yuri Pechatnov <yuri.pechatnov@gmail.com>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

