#!/bin/bash

# put config in the right place
.   /etc/wb_env.sh

CONFFILE="/etc/wb-homa-rfsniffer.conf"

BOARD_CONF_PREFIX="/usr/share/wb-homa-rfsniffer/wb-homa-rfsniffer.conf."

SUFFIX=$WB_VERSION
BOARD_CONF="${BOARD_CONF_PREFIX}${SUFFIX}"

if ! [ -f $BOARD_CONF ]; then
    SUFFIX="default"
    BOARD_CONF="${BOARD_CONF_PREFIX}${SUFFIX}"
fi

ucf --debconf-ok $BOARD_CONF $CONFFILE


# launch driver

update-rc.d wb-homa-rfsniffer defaults
invoke-rc.d wb-homa-rfsniffer start
